### ISSUE TITLE
Need a better icon for the new tile

### ISSUE THREAD

**Issue by djowett** [collective/covertile.cycle2#3]
You can see I'm not a designer, right?...
https://github.com/collective/covertile.cycle2/blob/master/src/covertile/cycle2/static/tile-cycle2-carousel.png

@hvelarde @agnogueira can you help?

**Comment by hvelarde** [comment]
why don't you just use the same carousel tile inside collective.cover?

https://github.com/collective/collective.cover/blob/master/src/collective/cover/static/tile-carousel.png

**Comment by djowett** [comment]
Just wanted to distinguish more obviously it from the standard carousel tile

But will leave it as you say for now

![icons_on_show](https://cloud.githubusercontent.com/assets/1470021/7070545/8f81de5a-ded7-11e4-8d53-f2bb001ff589.png)

**Comment by hvelarde** [comment]
I think is ok; you are not going to use both carousel tiles, right?

we can think about this later.

**Comment by djowett** [comment]
I won't do myself. But if c.cover will not have the galleria carousel removed by the time we release this, then I would not want other folk to be confused.

Perhaps this product should make sure the galleria carousel in c.cover is removed from "Available tiles"?

**Comment by hvelarde** [comment]
I think it would be better to just pin the add-on to depend on `collective.cover >= 1.0b1` after we make the release.

**Comment by djowett** [comment]
@hvelarde what's the timescale for collective.cover 1.0b1?   I think covertile.cycle2 is ready to go now, though I can wait a week or so.

**Comment by hvelarde** [comment]
we need to spin off the carousel tile first

**Comment by djowett** [comment]
Not an 'issue', so closing
