### ISSUE TITLE
Any hints for layout configuration form?

### ISSUE THREAD

**Issue by djowett** [collective/covertile.cycle2#4]
There's a few things I'm not sure how to do in the configuration view:
1. hide Date & Description fields (can I reomit an no_omit?)
2. stop reordering of fields (it won't affect anything)
3. remove the visibility option on some fields (title, image & number of items to display)

If there's easy solutions please let me know!

**Comment by hvelarde** [comment]
I was talking about this with @leorochael today; what we really need to do is provide a new mode for z3c.form widgets (configuration): https://pythonhosted.org/z3c.form/widget.html

everything will be easier if we do that on collective.cover and we will get rid of a lot of insane code.

we should think about it and open a new ticket.

**Comment by djowett** [comment]
I'm not an expert in this, but it doesn't require a change in z3c.form does it?  From your link...

> We can now register the template factory. The name of the factory is the mode of the widget. By  default, there are two widget modes: “input” and “display”. However, **since the mode is just a string**, one can develop other kinds of modes as needed for a project. The default mode is “input”:'

**Comment by djowett** [comment]
@hvelarde Ok my solution to 1 was [not to inherit the schema from IListTile](https://github.com/collective/covertile.cycle2/blob/master/src/covertile/cycle2/tiles/carousel.py#L37).   The object CarouselTile still inherits from ListTile.  I hope that's OK - it's seems fine in tests.
Issues 2 & 3 I'm ignoring for now.

**Comment by hvelarde** [comment]
seems fine to me as long as you left some documentation in the code for later review ;-)
